site_name: OptimaV2 Document
site_url: "https://example.enerzai.com/optimav2"
repo_url: "https://github.com/ENERZAi/OptimaV2-Docs"
nav:
  - Home: index.md
  - About: about.md
  - "User Guide":
    - "Install": "guide/install.md"
    - "Convert": "guide/convert.md"
    - "Inference": "guide/inference.md"
  - "Opto Language":
    - "Builtin Functions": "kernel/builtin.md"
  - "Runtime API":
    - Functions: "runtime/functions.md"
theme: readthedocs
plugins:
  - section-index
markdown_extensions:
  - footnotes
