site_name: OptimaV2 Document
site_url: "https://example.enerzai.com/optimav2"
repo_url: "https://github.com/ENERZAi/OptimaV2-Docs"
nav:
  - Home: index.md
  - About: about.md
  - "User Guide":
    - "Install": "guide/install.md"
    - "Convert": "guide/convert.md"
    - "Inference": "guide/inference.md"
  - "Opto Language":
    - "Builtin Functions": "kernel/builtin.md"
    - "About" : "kernel/about.md"
    - "Tutorial" : 
      - "Basics" : "kernel/Tutorial/Basics.md"
      - "Chapter1" : "kernel/Tutorial/Chapter1.md"
      - "Chapter2" : "kernel/Tutorial/Chapter2.md"
      - "Chapter3" : "kernel/Tutorial/Chapter3.md"
      - "Chapter4" : "kernel/Tutorial/Chapter4.md"
      - "Chapter5" : "kernel/Tutorial/Chapter5.md"
      - "Chapter6" : "kernel/Tutorial/Chapter6.md"
  - "Runtime API Reference":
    - "C++": "runtime/cpp.md"
    - "Python": "runtime/python.md"
theme: readthedocs
extra_css:
  - "template/style.css"
extra_javascript:
  - "template/sync-tabs.js"
plugins:
  - section-index
markdown_extensions: 
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
